# Generated by Django 5.2.8 on 2025-11-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('credit_en_cours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_achats', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('specialite', models.CharField(max_length=200)),
                ('total_commandes_mois', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('credit_30j', 'Crédit 30j')], max_length=20)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('en_attente', 'En attente')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('livraison_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livree', 'Livrée')], max_length=20)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('seuil', models.IntegerField(default=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categorie')),
            ],
        ),
    ]
