# Generated by Django 5.2.8 on 2025-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='categorie',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
