# Generated by Django 5.2.8 on 2025-11-20 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_categorie_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Modes de Paiement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['-date_creation'], 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.modepaiement'),
        ),
    ]
