# Generated by Django 5.2.7 on 2025-10-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.CharField()),
                ('adress', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=300)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
    ]
