# Generated by Django 5.2.7 on 2025-11-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default='500', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.CharField(max_length=500),
        ),
    ]
