# Generated by Django 5.2.7 on 2025-11-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande_total_alter_commande_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_promo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('especes', 'Espèces à la livraison')], default='mobile_money', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='reduction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='sous_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(default=500, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='zipcode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
