# Generated by Django 5.2.7 on 2025-11-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commande_code_promo_commande_date_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('reduction_pourcentage', models.FloatField(default=0)),
                ('reduction_montant', models.FloatField(default=0)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('utilisations_max', models.IntegerField(default=100)),
                ('utilisations_actuelles', models.IntegerField(default=0)),
            ],
        ),
    ]
